/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.actvn.java06.UI;

import com.actvn.java06.FileSave;
import com.actvn.java06.MonthlyTicket;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import static com.actvn.java06.PoolManage.monthlyTickets;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thepo
 */
public class SellMonthlyTicket extends javax.swing.JFrame {

    /**
     * Creates new form SellMonthlyTicket
     */
    private String customerNameValue;
    private String customerAddressValue;
    private String ticketIdValue;
    private int customerPhoneValue;
    private int customerAgeValue;
    private LocalDate registerDate;
    private LocalDate expiredDate;
    private String isVipTicket;
    private double ticketPrice;
    private MonthlyTicket ticket = new MonthlyTicket();

    public SellMonthlyTicket() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setJDateChooser();
        addPlaceholder(jInputName);
        addPlaceholder(jInputAddress);
        addPlaceholder(jInputPhone);
        addPlaceholder(jInputAge);
        try {
            ticketIdValue = handleTicketId();
            txtTicketId.setText(ticketIdValue);
        } catch (IOException ex) {
            Logger.getLogger(SellMonthlyTicket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void addPlaceholder(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }

    public void removePlaceholder(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    public int getTicketId() throws IOException {
        int index = -1;
        index = FileSave.ReadIndexOfMonthlyTicket(index);
        index++;
        return index;
    }

    public String handleTicketId() throws IOException {
        int index = getTicketId();
        ticketIdValue = ticket.creatTicketID(index);
        return ticketIdValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInputName = new javax.swing.JTextField();
        jInputAddress = new javax.swing.JTextField();
        jInputPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jInputAge = new javax.swing.JTextField();
        txtWarnName = new javax.swing.JLabel();
        txtWarnAddress = new javax.swing.JLabel();
        txtWarnPhone = new javax.swing.JLabel();
        txtWarnAge = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRegisterDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSelectOneMonth = new javax.swing.JRadioButton();
        jSelectThreeMonth = new javax.swing.JRadioButton();
        jSelectSixMonth = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jSelectNormalTicket = new javax.swing.JRadioButton();
        jSelectVipTicket = new javax.swing.JRadioButton();
        txtExpiredDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTicketId = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        jSubmitButton = new javax.swing.JButton();
        jResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Đăng ký vé tháng");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên khách hàng:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Địa chỉ: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại: ");

        jInputName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jInputName.setText("Họ và tên*");
        jInputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputNameFocusLost(evt);
            }
        });
        jInputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputNameActionPerformed(evt);
            }
        });

        jInputAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jInputAddress.setText("Địa chỉ*");
        jInputAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputAddressFocusLost(evt);
            }
        });
        jInputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputAddressActionPerformed(evt);
            }
        });

        jInputPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jInputPhone.setText("Số điện thoại*");
        jInputPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputPhoneFocusLost(evt);
            }
        });
        jInputPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputPhoneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Tuổi:");

        jInputAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jInputAge.setText("Tuổi*");
        jInputAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputAgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputAgeFocusLost(evt);
            }
        });
        jInputAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInputName)
                    .addComponent(jInputAddress)
                    .addComponent(jInputPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(txtWarnName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWarnAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWarnPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtWarnAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInputAge))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWarnName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jInputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWarnAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jInputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWarnPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtWarnAge)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin vé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ngày bắt đầu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Ngày kết thúc: ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gia hạn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jSelectOneMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectOneMonth.setText("1 tháng");
        jSelectOneMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectOneMonthActionPerformed(evt);
            }
        });

        jSelectThreeMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectThreeMonth.setText("3 tháng");
        jSelectThreeMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectThreeMonthActionPerformed(evt);
            }
        });

        jSelectSixMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectSixMonth.setText("6 tháng");
        jSelectSixMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectSixMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSelectOneMonth)
                    .addComponent(jSelectThreeMonth)
                    .addComponent(jSelectSixMonth))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSelectOneMonth)
                .addGap(18, 18, 18)
                .addComponent(jSelectThreeMonth)
                .addGap(18, 18, 18)
                .addComponent(jSelectSixMonth)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại vé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jSelectNormalTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectNormalTicket.setText("Thường");
        jSelectNormalTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectNormalTicketActionPerformed(evt);
            }
        });

        jSelectVipTicket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectVipTicket.setText("Vip");
        jSelectVipTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectVipTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSelectVipTicket)
                    .addComponent(jSelectNormalTicket))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSelectNormalTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSelectVipTicket)
                .addGap(25, 25, 25))
        );

        txtExpiredDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Giá vé:");

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mã vé:");

        txtTicketId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRegisterDate, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(txtExpiredDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTicketId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTicketId))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jRegisterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpiredDate)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrice))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jExitButton.setText("Thoát");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSubmitButton.setText("Xác nhận");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        jResetButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jResetButton.setText("Hủy");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSubmitButton)
                        .addGap(18, 18, 18)
                        .addComponent(jResetButton)
                        .addGap(2, 2, 2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExitButton)
                    .addComponent(jSubmitButton)
                    .addComponent(jResetButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputNameActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_jInputNameActionPerformed

    private void jInputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputAddressActionPerformed

    private void jInputPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputPhoneActionPerformed

    private void jInputNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputNameFocusGained
        // TODO add your handling code here:
        if (jInputName.getText().equals("Họ và tên*")) {
            jInputName.setText(null);
            jInputName.requestFocus();
            removePlaceholder(jInputName);
        }
    }//GEN-LAST:event_jInputNameFocusGained

    private void jInputAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputAddressFocusGained
        // TODO add your handling code here:
        if (jInputAddress.getText().equals("Địa chỉ*")) {
            jInputAddress.setText(null);
            jInputAddress.requestFocus();
            removePlaceholder(jInputAddress);
        }
    }//GEN-LAST:event_jInputAddressFocusGained

    private void jInputPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPhoneFocusGained
        // TODO add your handling code here:
        if (jInputPhone.getText().equals("Số điện thoại*")) {
            jInputPhone.setText(null);
            jInputPhone.requestFocus();
            removePlaceholder(jInputPhone);
        }
    }//GEN-LAST:event_jInputPhoneFocusGained

    private void jInputNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputNameFocusLost
        // TODO add your handling code here:
        if (jInputName.getText().length() == 0) {
            addPlaceholder(jInputName);
            jInputName.setText("Họ và tên*");
        }
    }//GEN-LAST:event_jInputNameFocusLost

    private void jInputAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputAddressFocusLost
        // TODO add your handling code here:
        if (jInputAddress.getText().length() == 0) {
            addPlaceholder(jInputAddress);
            jInputAddress.setText("Địa chỉ*");
        }
    }//GEN-LAST:event_jInputAddressFocusLost

    private void jInputPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPhoneFocusLost
        // TODO add your handling code here:
        if (jInputPhone.getText().length() == 0) {
            addPlaceholder(jInputPhone);
            jInputPhone.setText("Số điện thoại*");
        }
    }//GEN-LAST:event_jInputPhoneFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jSelectOneMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectOneMonthActionPerformed
        // TODO add your handling code here:
        jSelectOneMonth.setSelected(true);
        jSelectThreeMonth.setSelected(false);
        jSelectSixMonth.setSelected(false);
        if (jRegisterDate.getDate() != null) {
            registerDate = fromDatetoLocalDate(jRegisterDate.getDate());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String formattedDate = registerDate.format(formatter);
            registerDate = LocalDate.parse(formattedDate, formatter);
            expiredDate = ticket.checkExpiedDate(registerDate, 1);
            String expiedDateString = dateFormaterApp(expiredDate);
            txtExpiredDate.setText(expiedDateString);
        }
    }//GEN-LAST:event_jSelectOneMonthActionPerformed

    private void jSelectThreeMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectThreeMonthActionPerformed
        // TODO add your handling code here:
        jSelectThreeMonth.setSelected(true);
        jSelectOneMonth.setSelected(false);
        jSelectSixMonth.setSelected(false);
        if (jRegisterDate.getDate() != null) {
            registerDate = fromDatetoLocalDate(jRegisterDate.getDate());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String formattedDate = registerDate.format(formatter);
            registerDate = LocalDate.parse(formattedDate, formatter);
            expiredDate = new MonthlyTicket().checkExpiedDate(registerDate, 3);
            String expiedDateString = dateFormaterApp(expiredDate);
            txtExpiredDate.setText(expiedDateString);
        }
    }//GEN-LAST:event_jSelectThreeMonthActionPerformed

    private void jSelectSixMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectSixMonthActionPerformed
        // TODO add your handling code here:
        jSelectSixMonth.setSelected(true);
        jSelectOneMonth.setSelected(false);
        jSelectThreeMonth.setSelected(false);
        if (jRegisterDate.getDate() != null) {
            registerDate = fromDatetoLocalDate(jRegisterDate.getDate());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String formattedDate = registerDate.format(formatter);
            registerDate = LocalDate.parse(formattedDate, formatter);
            expiredDate = new MonthlyTicket().checkExpiedDate(registerDate, 6);
            String expiedDateString = dateFormaterApp(expiredDate);
            txtExpiredDate.setText(expiedDateString);
        }
    }//GEN-LAST:event_jSelectSixMonthActionPerformed

    private void jSelectNormalTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectNormalTicketActionPerformed
        // TODO add your handling code here:
        jSelectNormalTicket.setSelected(true);
        jSelectVipTicket.setSelected(false);
        if (jRegisterDate.getDate() != null && jSelectSixMonth.isSelected()) {
            ticketPrice = ticket.caculatorMonthlyPrice("N", Integer.parseInt(jInputAge.getText())) * 6 - 200000;
            txtPrice.setText(String.valueOf(ticketPrice));
        } else if (jRegisterDate.getDate() != null && jSelectThreeMonth.isSelected()) {
            ticketPrice = ticket.caculatorMonthlyPrice("N", Integer.parseInt(jInputAge.getText())) * 3 - 100000;
            txtPrice.setText(String.valueOf(ticketPrice));
        } else {
            ticketPrice = ticket.caculatorMonthlyPrice("N", Integer.parseInt(jInputAge.getText()));
            txtPrice.setText(String.valueOf(ticketPrice));
        }
        isVipTicket = "Normal";
    }//GEN-LAST:event_jSelectNormalTicketActionPerformed

    private void jSelectVipTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectVipTicketActionPerformed
        // TODO add your handling code here:
        jSelectVipTicket.setSelected(true);
        jSelectNormalTicket.setSelected(false);
        if (jRegisterDate.getDate() != null && jSelectSixMonth.isSelected()) {
            ticketPrice = ticket.caculatorMonthlyPrice("V", Integer.parseInt(jInputAge.getText())) * 6 - 200000;
            txtPrice.setText(String.valueOf(ticketPrice));
        } else if (jRegisterDate.getDate() != null && jSelectThreeMonth.isSelected()) {
            ticketPrice = ticket.caculatorMonthlyPrice("V", Integer.parseInt(jInputAge.getText())) * 3 - 100000;
            txtPrice.setText(String.valueOf(ticketPrice));
        } else {
            ticketPrice = ticket.caculatorMonthlyPrice("V", Integer.parseInt(jInputAge.getText()));
            txtPrice.setText(String.valueOf(ticketPrice));
        }
        isVipTicket = "Vip";
    }//GEN-LAST:event_jSelectVipTicketActionPerformed

    private void jInputAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputAgeActionPerformed

    private void jInputAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputAgeFocusGained
        // TODO add your handling code here:
        if (jInputAge.getText().equals("Tuổi*")) {
            jInputAge.setText(null);
            jInputAge.requestFocus();
            removePlaceholder(jInputAge);
        }
    }//GEN-LAST:event_jInputAgeFocusGained

    private void jInputAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputAgeFocusLost
        // TODO add your handling code here:
        if (jInputAge.getText().length() == 0) {
            addPlaceholder(jInputAge);
            jInputAge.setText("Tuổi*");
        }
    }//GEN-LAST:event_jInputAgeFocusLost

    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        boolean validate = validateMonthlyForm();
        if (validate == true) {
            if (jSelectNormalTicket.isSelected()) {
                isVipTicket = "Normal";
            }
            if (jSelectVipTicket.isSelected()) {
                isVipTicket = "Vip";
            }
            getCustomerValue();
            ticket.setTicketID(ticketIdValue);
            ticket.setCustomerName(customerNameValue);
            ticket.setCustomerAddress(customerAddressValue);
            ticket.setAge(customerAgeValue);
            ticket.setIsTicketVip(isVipTicket);
            ticket.setCustomerPhone(customerPhoneValue);
            ticket.setRegistereDate(registerDate);
            ticket.setExpiedDate(expiredDate);
            ticket.setMonthlyPrice(ticketPrice);
            monthlyTickets.add(ticket);
            try {
                FileSave.saveMonthlyTicket(ticket);
                JOptionPane.showMessageDialog(this, "Lưu thành công!");
            } catch (Exception e) {
                e.printStackTrace();
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Không được để trống thông tin");
        }
    }//GEN-LAST:event_jSubmitButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public LocalDate fromDatetoLocalDate(Date date) {
        return date.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
    }

    public void setJDateChooser() {
        jRegisterDate.setDateFormatString("dd-MM-yyyy");
    }

    public String dateFormaterApp(LocalDate date) {
        DateTimeFormatter formatString = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String result = date.format(formatString);
        return result;
    }

    public LocalDate fromStringToLocalDate(String data) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate date = LocalDate.parse(data, formatter);
        return date;
    }

    public void getCustomerValue() {
        customerNameValue = jInputName.getText();
        customerAddressValue = jInputAddress.getText();
        customerPhoneValue = Integer.parseInt(jInputPhone.getText());
        customerAgeValue = Integer.parseInt(jInputAge.getText());
    }

    public boolean validateMonthlyForm() {

        if (jInputName.equals("Họ và tên*")
                || jInputAddress.equals("Địa chỉ*")
                || jInputPhone.getText().equals("Số điện thoại*")
                || jInputAge.getText().equals("Tuổi*")
                || jRegisterDate.getDate() == null) {
            return false;
        } else {
            return true;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMonthlyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMonthlyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMonthlyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMonthlyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMonthlyTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExitButton;
    private javax.swing.JTextField jInputAddress;
    private javax.swing.JTextField jInputAge;
    private javax.swing.JTextField jInputName;
    private javax.swing.JTextField jInputPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JDateChooser jRegisterDate;
    private javax.swing.JButton jResetButton;
    private javax.swing.JRadioButton jSelectNormalTicket;
    private javax.swing.JRadioButton jSelectOneMonth;
    private javax.swing.JRadioButton jSelectSixMonth;
    private javax.swing.JRadioButton jSelectThreeMonth;
    private javax.swing.JRadioButton jSelectVipTicket;
    private javax.swing.JButton jSubmitButton;
    private javax.swing.JLabel txtExpiredDate;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTicketId;
    private javax.swing.JLabel txtWarnAddress;
    private javax.swing.JLabel txtWarnAge;
    private javax.swing.JLabel txtWarnName;
    private javax.swing.JLabel txtWarnPhone;
    // End of variables declaration//GEN-END:variables
}
