/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.actvn.java06.UI;

/**
 *
 * @author thepo
 */
public class TicketStatistic extends javax.swing.JFrame {

    /**
     * Creates new form TicketStatistic
     */
    public TicketStatistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jListCurrentDay = new javax.swing.JMenu();
        jListDailyCurrentDay = new javax.swing.JMenuItem();
        jListDailyByDate = new javax.swing.JMenuItem();
        jListDailyByTimeSlot = new javax.swing.JMenuItem();
        jPriceByTimeSlot = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jListMonthlyByMonth = new javax.swing.JMenuItem();
        jPriceByMonth = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jListCurrentDay.setText("Vé ngày");
        jListCurrentDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jListDailyCurrentDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListDailyCurrentDay.setText("Danh sách vé trong ngày");
        jListCurrentDay.add(jListDailyCurrentDay);

        jListDailyByDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListDailyByDate.setText("Danh sách vé theo ngày");
        jListCurrentDay.add(jListDailyByDate);

        jListDailyByTimeSlot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListDailyByTimeSlot.setText("Danh sách vé theo khung giờ");
        jListCurrentDay.add(jListDailyByTimeSlot);

        jPriceByTimeSlot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPriceByTimeSlot.setText("Tổng thu nhập theo khung giờ");
        jListCurrentDay.add(jPriceByTimeSlot);

        jMenuBar1.add(jListCurrentDay);

        jMenu2.setText("Vé tháng");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jListMonthlyByMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jListMonthlyByMonth.setText("Danh sách theo tháng");
        jMenu2.add(jListMonthlyByMonth);

        jPriceByMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPriceByMonth.setText("Thống kê thu nhập theo tháng");
        jMenu2.add(jPriceByMonth);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketStatistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jListCurrentDay;
    private javax.swing.JMenuItem jListDailyByDate;
    private javax.swing.JMenuItem jListDailyByTimeSlot;
    private javax.swing.JMenuItem jListDailyCurrentDay;
    private javax.swing.JMenuItem jListMonthlyByMonth;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jPriceByMonth;
    private javax.swing.JMenuItem jPriceByTimeSlot;
    // End of variables declaration//GEN-END:variables
}
